DROP TABLE IF EXISTS User CASCADE;
CREATE TABLE User (
  `userID` INT(4) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `hash` VARCHAR(40) NOT NULL DEFAULT '87fc4e805a0db57662fa3cb86a252c41661a8374',
  `f_name` VARCHAR(32) NULL,
  `l_name` VARCHAR(32) NULL,
  `isActive` TINYINT NOT NULL DEFAULT 0,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE)
);
